"""P206 -- P133's bottleneck 4 is FINDING_P52's N1, rediscovered 8 days later.

PRIOR ART, FOUND ONLY AFTER THE DERIVATION BELOW WAS COMPLETE. This file
does not establish a new theorem. `FINDING_P52` (2026-08-16) already
computed the same one-dimensional field-normalization redundancy for the
committed monopole action, already derived `A g^2` from its null vector as
an invariant, and already corrected the terminology this file's own first
draft got wrong: it is **field-normalization redundancy / field-
redefinition covariance**, NOT "gauge" -- there is no local gauge symmetry
here, only a reparametrization freedom of one scalar field's
normalization. `FINDING_P133` (2026-08-24) then computed rank 2 for
`O1 = A g^2`, `O2 = A kappa^2`, `O3 = kappa/g` and named it "structural
non-identifiability," a project bottleneck -- without connecting it to
P52's result from eight days earlier. All three of P133's observables are
P52 invariants; P133's rank deficiency IS P52's nullity.

So the contribution here is a connection, not a discovery: the bottleneck
was built on top of an already-derived and already-documented property of
the project's own action. That is worth recording precisely because the
project's own memory-protocol warns about exactly this -- the same result
rediscovered under a different name.

INHERITED CONDITIONALITY. P52's own verdict is CONDITIONAL ("N1 holds only
given which coefficients are stipulated"), and its KG2 stands: form
invariance is not value determination. Nothing below escapes either limit.
What follows therefore reads: *given* P52's N1, P133's rank-2 is complete
rather than deficient -- and the genuinely open question is P52's KG2 (the
numerical values of the invariants), which is NOT the question P133 posed.

WHAT THIS SUPERSEDES (no-silent-correction; the whole chain is recorded
because each step's error is what produced the next step's question):

  draft 1 -- claimed a chain of n propagators has v = n+1 coupling
    insertions, hence every n>=2 observable breaks P133's degeneracy.
    WRONG: a chain over n+1 bodies puts TWO insertions on each interior
    body, so v = 2n. Caught by recounting.
  draft 2 -- corrected to v = 2n, concluded the degeneracy is unbreakable
    for linear-in-phi couplings and that a phi^2 (polarizability) vertex
    escapes it with L = +1. A context-blind skeptic pass CONFIRMED the
    combinatorics but WEAKENED the escape claim: a phi^2 vertex carries a
    NEW coupling alpha, so the honest count is A^n alpha^m g^b kappa^c
    with b+c = 2n-2m, and the problem moves to a 4-parameter space.
  draft 3 (this file) -- re-checking the skeptic's own proposed fix
    ("two independent phi^2 observables give rank 4") showed it is FALSE:
    the rank stays 3 no matter how many are added, at any n, at any m.
    Asking WHY produced the actual result below. The skeptic was right
    that draft 2 was wrong, and wrong about the repair.

THE RESULT

The residual degeneracy is not a shortage of observables. It is a fixed
one-dimensional direction in log-parameter space,

    v = (-1, 1/2, 1/2, 1)   in   (log A, log g, log kappa, log alpha)

which is exactly the redundancy generated by rescaling the field itself.
Substituting phi = lambda * phibar into the action:

    (1/2A)(d phi)^2   ->   Abar   = A / lambda^2
    g * m * phi       ->   gbar   = g * lambda
    kappa * (..) * phi->   kappabar = kappa * lambda
    alpha * phi^2     ->   alphabar = alpha * lambda^2

so (A, g, kappa, alpha) and (A/l^2, g*l, kappa*l, alpha*l^2) are THE SAME
THEORY. No measurement can distinguish them, because there is nothing to
distinguish.

Consequences, each verified below rather than asserted:

  1. P133's rank 2 out of 3 is not a deficiency. The theory has 3
     parameters, 1 redundancy direction, and therefore 2 physical
     degrees of freedom -- and P133's three observables determine both.
     The observable set was already complete.
  2. P205's break functional L = 2a - b - c is precisely (minus twice)
     the pairing with v. So L = 0 <=> the monomial is rescaling-INVARIANT
     <=> it is a well-defined physical quantity at all.
  3. Therefore P205's "escapes" invert: an observable with L != 0 breaks
     the degeneracy only because it is NOT rescaling-invariant, i.e. its
     value depends on an arbitrary convention. "Measure A directly" is
     not an experiment; it is a choice of normalization convention.
  4. With a phi^2 vertex the count is 4 parameters, still 1 redundancy
     direction, 3 physical -- and ONE polarizability observable already
     reaches rank 3. Complete identification modulo the redundancy,
     which is why adding more never helps. SCOPE (both skeptics, same
     point independently): this holds within the vertex class
     {g*m*phi, kappa*q*phi, alpha*phi^2}. Introducing a vertex of a
     different power (phi^3, phi^4) adds a parameter with its own
     weight, and the rank arithmetic must be redone -- "adding more
     never helps" is about further phi^2 observables, not about any
     conceivable extension of the action.

NOT_VALIDATION * NOT_REFUTATION * OUR_RECONSTRUCTION * NO_AUTHOR_ERROR
"""

from __future__ import annotations

import itertools

import sympy as sp

A, G, K, AL = sp.symbols("A g kappa alpha", positive=True)
LAM = sp.Symbol("lambda", positive=True)

# FINDING_P133's own three observables, as exponent tuples in (A, g, kappa).
P133_3: list[tuple[tuple[int, int, int], str]] = [
    ((1, 2, 0), "O1 = A g^2      monopole-monopole"),
    ((1, 0, 2), "O2 = A kappa^2  dipole-dipole"),
    ((0, -1, 1), "O3 = kappa / g  cross-sector ratio (eta)"),
]
P133_4 = [(a, b, c, 0) for (a, b, c), _ in P133_3]

# The field rescaling phi -> lambda * phibar, as exponents of lambda on
# each parameter. Derived in the docstring, verified in check_rescaling().
RESCALING = {"A": -2, "g": 1, "kappa": 1, "alpha": 2}


def mono4(t: tuple[int, int, int, int]) -> sp.Expr:
    a, b, c, d = t
    return A**a * G**b * K**c * AL**d


def rank4(ts: list[tuple[int, int, int, int]]) -> int:
    return sp.Matrix([mono4(t) for t in ts]).jacobian([A, G, K, AL]).rank()


def rank3(ts: list[tuple[int, int, int]]) -> int:
    rows = [A**a * G**b * K**c for a, b, c in ts]
    return sp.Matrix(rows).jacobian([A, G, K]).rank()


def rescale(expr: sp.Expr) -> sp.Expr:
    """Apply phi -> lambda*phibar, i.e. the induced parameter redefinition."""
    # WHY uniform `* LAM ** weight` for all four: an earlier version wrote A's
    # case as `A / LAM ** abs(RESCALING["A"])`. That gave the right answer for
    # the right weight, but silently ignored the stored sign -- flipping
    # RESCALING["A"] to +2 would have changed nothing. Skeptic A flagged it as a
    # silent-corruption path under refactor. Fixed to read the sign it stores.
    return sp.simplify(
        expr.subs(
            {
                A: A * LAM ** RESCALING["A"],
                G: G * LAM ** RESCALING["g"],
                K: K * LAM ** RESCALING["kappa"],
                AL: AL * LAM ** RESCALING["alpha"],
            },
            simultaneous=True,
        )
    )


def phi2_family(n: int, m: int) -> list[tuple[int, int, int, int]]:
    """n propagators, m phi^2 vertices: 2n ends, 2m consumed by the phi^2
    vertices (two each), the remaining 2n-2m carrying g or kappa."""
    rest = 2 * n - 2 * m
    return [] if rest < 0 else [(n, b, rest - b, m) for b in range(rest + 1)]


def section(title: str) -> None:
    print(f"\n{'=' * 70}\n{title}\n{'=' * 70}")


def main() -> int:  # noqa: PLR0915  (a linear verification script, read top to bottom)
    section("P206 -- P133's degeneracy is the field-rescaling redundancy")

    # ---- PC1: reproduce P133 -------------------------------------------
    r0 = rank3([e for e, _ in P133_3])
    print(f"\nPC1 [positive control] rank of P133's own three observables: {r0}")
    assert r0 == 2, f"expected P133's rank 2, got {r0}"
    print("     reproduces FINDING_P133. Control PASSES.")

    # ---- PC2: the machinery can detect rank 3 when it is there ---------
    r_full = rank3([(1, 0, 0), (0, 1, 0), (0, 0, 1)])
    print(f"\nPC2 [negative control] rank of the bare parameters themselves: {r_full}")
    assert r_full == 3, "rank machinery is broken -- it cannot see rank 3"
    print("     rank 2 above is a real finding, not a broken computation. PASSES.")

    # ---- The rescaling is an exact invariance of P133's observables -----
    section("R1 -- P133's three observables are rescaling-INVARIANT")
    print("  phi -> lambda*phibar induces A->A/l^2, g->g*l, kappa->kappa*l.\n")
    for e, lab in P133_3:
        expr = mono4((*e, 0))
        ratio = sp.simplify(rescale(expr) / expr)
        print(f"     {lab:34s} rescaled/original = {ratio}")
        assert ratio == 1, f"{lab} is NOT rescaling-invariant"
    print("\n  All three are exactly invariant: they are physical quantities.")

    # ---- ...and the "break-condition" observables are NOT --------------
    section("R2 -- every observable that BREAKS the degeneracy is NOT invariant")
    print("  P205: rank rises iff L = 2a - b - c != 0. Check what those are:\n")
    for e, lab in [((1, 0, 0), "A alone"), ((0, 1, 0), "g alone"), ((0, 0, 1), "kappa alone")]:
        expr = mono4((*e, 0))
        ratio = sp.simplify(rescale(expr) / expr)
        lval = 2 * e[0] - e[1] - e[2]
        broke = rank3([x for x, _ in P133_3] + [e]) == 3
        print(f"     {lab:12s} L={lval:2d}  breaks={broke}  rescaled/original = {ratio}")
        assert lval != 0 and broke
        assert ratio != 1, f"{lab} unexpectedly IS invariant"
    print("\n  Each 'escape' is convention-dependent. Measuring it is not an")
    print("  experiment -- its value is set by an arbitrary convention.")

    # ---- L is exactly the pairing with the redundancy direction --------------
    section("R3 -- L = 2a - b - c IS the rescaling pairing, not a coincidence")
    print("  Under phi->lambda*phibar, A^a g^b kappa^c picks up")
    print("  lambda^(-2a + b + c) = lambda^(-L). So L = 0 <=> invariant.\n")
    checked = 0
    for a, b, c in itertools.product(range(-2, 3), repeat=3):
        expr = mono4((a, b, c, 0))
        power = sp.simplify(sp.log(rescale(expr) / expr) / sp.log(LAM))
        assert sp.simplify(power - (-(2 * a - b - c))) == 0, f"L identity failed at {(a, b, c)}"
        checked += 1
    print(f"     CHECKED (not proved) on {checked} triples in [-2,2]^3: exact.")
    print("     The proof is algebraic and holds for ALL real exponents:")
    print("       (A/l^2)^a (g l)^b (k l)^c = A^a g^b k^c * l^(b+c-2a).")
    print("     This loop tests sympy's cancellation, not the mathematics.")
    print("     L != 0 is therefore NOT 'more informative' -- it is")
    print("     'not well-defined'. P205's criterion selects exactly the")
    print("     quantities that are not observables.")

    # ---- The rank is complete, not deficient ---------------------------
    section("R4 -- rank 2 IS complete: 3 parameters minus 1 redundancy")
    M3 = sp.Matrix([e for e, _ in P133_3])
    ns3 = M3.nullspace()
    print(f"     exponent matrix rank      = {M3.rank()}")
    print(f"     null space dimension      = {len(ns3)}")
    assert len(ns3) == 1
    nv = sp.Matrix(ns3[0]) / ns3[0][0] * -1  # normalize first entry to -1
    print(f"     null direction (normalized) = {nv.T.tolist()[0]}")
    expected = sp.Matrix([-1, sp.Rational(1, 2), sp.Rational(1, 2)])
    assert sp.simplify(nv - expected) == sp.zeros(3, 1), f"got {nv.T}, expected {expected.T}"
    print("     matches the rescaling generator (-1, 1/2, 1/2) exactly.")
    print("\n     => 3 parameters - 1 redundancy = 2 physical d.o.f.,")
    print("        and P133's observables determine all 2. NOTHING IS MISSING.")

    # ---- The 4-parameter case behaves the same way ---------------------
    section("R5 -- with a phi^2 vertex: 4 params, 1 redundancy, 3 physical")
    print(f"     P133 alone in (A,g,kappa,alpha):  rank {rank4(P133_4)}  (alpha unconstrained)")
    fam = phi2_family(2, 1)
    print(f"     one phi^2 observable {fam[0]}:      rank {rank4(P133_4 + [fam[0]])}")
    assert rank4(P133_4 + [fam[0]]) == 3
    print("\n     Adding MORE never helps -- checked across n and m:")
    for n, m in [(2, 1), (3, 1), (3, 2), (4, 1), (4, 2)]:
        f = phi2_family(n, m)
        if not f:
            continue
        best = max(rank4(P133_4 + list(s)) for s in itertools.combinations(f, min(2, len(f))))
        print(f"       n={n} m={m}: best rank with any two of them = {best}")
        assert best == 3, f"unexpected rank {best} for n={n} m={m}"
    M4 = sp.Matrix([*P133_4, fam[0]])
    ns4 = M4.nullspace()
    nv4 = sp.Matrix(ns4[0]) / ns4[0][0] * -1
    print(f"\n     residual null direction = {nv4.T.tolist()[0]}")
    assert sp.simplify(nv4 - sp.Matrix([-1, sp.Rational(1, 2), sp.Rational(1, 2), 1])) == sp.zeros(
        4, 1
    )
    print("     = the SAME rescaling direction, now including alpha.")
    print("     rank 3 of 4 is again complete, modulo the same redundancy.")

    section("CONCLUSION")
    print("  Bottleneck 4 as posed -- 'find an observable that identifies")
    print("  (A, g, kappa) separately' -- has no solution, and needs none.")
    print("  Within this action and absent any external anchoring of phi's")
    print("  normalization, A is not separately measurable: it is absorbed")
    print("  into how phi is normalized. The rank-2 result that looked")
    print("  like a measurement gap is a complete determination of a")
    print("  2-parameter physical theory written in 3 redundant coordinates.")
    print()
    print("  This is FINDING_P52's N1, restated for P133's observable set.")
    print("  It is a connection between two of this project's own results,")
    print("  not a new theorem -- see the docstring's PRIOR ART note.")
    print()
    print("  What this does NOT establish:")
    print("   - anything about whether the action itself is right;")
    print("   - that A is meaningless in general. The claim is scoped to")
    print("     THIS action with no external anchor. If phi's normalization")
    print("     is pinned from outside -- a canonical kinetic term fixed by")
    print("     another sector, a VEV, an LSZ anchor -- A regains an")
    print("     operational value and the scoping must be restated;")
    print("   - anything about non-monomial or non-perturbative observables")
    print("     (the rescaling argument covers the action's parameters, but")
    print("     the exhaustiveness check here is over monomials);")
    print("   - that the 2 remaining physical parameters have DETERMINED")
    print("     VALUES. That is P52's own KG2, explicitly still open:")
    print("     form invariance is not value determination. P133 did not")
    print("     ask that question, and this file does not answer it.")
    print("=" * 70)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
